[libraries]
jacop       = { group = "org.jacop" , name = "jacop"      , version = "4.10.0"   }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version = "3.51.1.0" }

[plugins]
shadow        = { id = "com.gradleup.shadow",           version = "9.3.1"  }
versions-plug = { id = "com.github.ben-manes.versions", version = "0.53.0" }
